image: php:7.1

stages:
  - tests
  - deploy

before_script:
  - apt-get update
  - apt-get install zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - mv composer.phar /usr/local/bin/composer

run_unit_tests:
  stage: tests
  script:
    - composer install --dev
    - ./vendor/bin/phpunit

deploy_to_production:
  environment:
    name: production
    url: http://www.developmentstudio.nl
  stage: deploy
  when: manual
  script:
    - composer install --no-dev
    - zip -r app.zip ./vendor ./public
  only:
    - master
  artifacts:
    paths:
      - public/
      - vendor/
